import type { Metadata } from "next";
import { Inter } from "next/font/google";
import './ui/globals.css'
import { PrimeReactProvider } from "primereact/api";
import "primereact/resources/primereact.css";
import "primeicons/primeicons.css";
import { StoreProvider } from "./lib/StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          <PrimeReactProvider>
            {children}
          </PrimeReactProvider>
        </body>
      </html>
    </StoreProvider>
  );
}
